name: sanityio_poc
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  flutter_svg: ^2.0.5
  http: ^1.2.0
  logger: ^1.4.0
  iconsax: ^0.0.8
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.2
  syncfusion_flutter_pdfviewer: ^24.2.4
  url_launcher: ^6.2.4
  intl: ^0.19.0
  webview_flutter: ^4.5.0
  rename_app: ^1.3.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Satoshi
      fonts:
        - asset: fonts/Satoshi-Regular.otf
        - asset: fonts/Satoshi-Italic.otf
          style: italic
        - asset: fonts/Satoshi-Medium.otf
        - asset: fonts/Satoshi-Bold.otf
    - family: iconsax
      fonts:
        - asset: fonts/iconsax.ttf

